name: sadio_mane_store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.14.0
  flutter_bloc: ^9.1.1
  internet_connection_checker_plus: ^2.7.2
  flutter_native_splash: ^2.4.6
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.7
  flutter_svg: ^2.2.0
  animate_do: ^4.2.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  flutter_zoom_drawer: ^3.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  firebase_messaging: ^15.2.9
  http: ^1.4.0
  jose: ^0.3.4
  googleapis_auth: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.4
  flutter_animate: ^4.5.2
  webview_flutter: ^4.13.0
  package_info_plus: ^8.3.0
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  bloc_concurrency: ^0.3.0
  flutter_local_notifications: ^19.4.1






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true

  assets:
    - secrets/env/
    - secrets/firebase_messaging_secret_key/
    - assets/images/png/
    - assets/images/svg/
    - assets/images/png/customer/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 300

flutter_assets:
  assets_path:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/png/admin/
    - assets/images/png/customer/

  output_path: lib/core/constants/
  filename: images_string.dart

flutter_intl:
  enabled: true