// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAChYCCmJ8KxLXZPN-o0gn0w6mCVMhnYQ4',
    appId: '1:614601275460:web:290c6c06fe297e933aa411',
    messagingSenderId: '614601275460',
    projectId: 'dalel-a7cf0',
    authDomain: 'dalel-a7cf0.firebaseapp.com',
    storageBucket: 'dalel-a7cf0.appspot.com',
    measurementId: 'G-KC7FWPCXPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6opgigJNLFe-eZqFMMngJQ0pbiApGrx8',
    appId: '1:614601275460:android:77a16e8066459fd03aa411',
    messagingSenderId: '614601275460',
    projectId: 'dalel-a7cf0',
    storageBucket: 'dalel-a7cf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZAbplSvvl5u4L0b6C3CmJ2nbi3BVAJdA',
    appId: '1:614601275460:ios:5263b1e52e61d28c3aa411',
    messagingSenderId: '614601275460',
    projectId: 'dalel-a7cf0',
    storageBucket: 'dalel-a7cf0.appspot.com',
    iosBundleId: 'com.sadiomanestore.sadioManeStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZAbplSvvl5u4L0b6C3CmJ2nbi3BVAJdA',
    appId: '1:614601275460:ios:5263b1e52e61d28c3aa411',
    messagingSenderId: '614601275460',
    projectId: 'dalel-a7cf0',
    storageBucket: 'dalel-a7cf0.appspot.com',
    iosBundleId: 'com.sadiomanestore.sadioManeStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPYMLA5SyoRmciLfHkWDVegjDtJEZW4kE',
    appId: '1:614601275460:web:669fabb84bd9bd463aa411',
    messagingSenderId: '614601275460',
    projectId: 'dalel-a7cf0',
    authDomain: 'dalel-a7cf0.firebaseapp.com',
    storageBucket: 'dalel-a7cf0.appspot.com',
    measurementId: 'G-G9E2F1G4GG',
  );
}
